mysite/apps/blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='bloglist'),
    path('<int:pk>/', BlogDetailView.as_view(), name='detail'),  # مسیر جزئیات
]

mysite/apps/comments/urls.py
from django.urls import path
from . import views
from .views import send_email_box,CommentListAndCreateComment,verify_email, send_verify_email

app_name = 'comments'

urlpatterns = [
    path('comment/verify/<uuid:code>/', views.verify_email, name='verify_comment'),#ارسال ایمیل به کاربر
    path('comment/send-verify/', views.send_verify_email, name='send_verify_email'),#تایید لینک در ایمیل 
    path('send_email_box/',send_email_box,name='send_email_box'),#باکس ارسال ایمیل
    path('comments/', CommentListAndCreateComment.as_view(), name='comments')#لیست کامنت ها و اضافه کردن کامنت جدید
]

mysite/apps/main/urls.py
from django.urls import path
from .views import index,ContactView,AboutView,ProjectsView,ResumeView

app_name = 'main'  
urlpatterns = [
    path('', index, name='index'),
    path('contact/',ContactView.as_view(), name='contact'),
    path('about/',AboutView.as_view(), name='about'),
    path('projects/',ProjectsView.as_view(), name='projects'),
    path('resume/',ResumeView.as_view(), name='resume'),
   
]

mysite/apps/skills/urls.py
from django.urls import path
from .views import SkillListView

app_name = 'skills'

urlpatterns = [
    path('', SkillListView.as_view(), name='skills-list'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.main.urls',namespace='main')),
    path('skills/', include('apps.skills.urls', namespace='skills')),
    path('blogs/', include('apps.blog.urls', namespace='blog')),
    path('comments/',include('apps.comments.urls',namespace='comments'))
   

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/templates/partials/footer.html
<!-- اول، در head اضافه کن -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"/>


<footer>
  <div class="footer-top">
    <div class="footer-top-left">
      Code your dreams
    </div>
    <div class="footer-top-right">
      <div class="footer-columns">
        <div class="container">
        <ul class="footer-follow">
          <li class="follow-title">Follow</li>
          <li><a href="https://www.instagram.com/kiarashseyedmohamadi" target="_blank"><i class="fab fa-instagram"></i> Instagram</a></li>
          <li><a href="https://www.linkedin.com/in/kiarash-seyedmohamadi-06b458377/" target="_blank"><i class="fab fa-linkedin"></i> LinkedIn</a></li>
          <li><a href="https://github.com/kiarashseyedmohamadi" target="_blank"><i class="fab fa-github"></i> GitHub</a></li>
        </ul>
        </div>
        <div class="container">
          <ul class="footer-follow">
            <li class="follow-title">Info</li>
            <li><a href="{% url 'main:contact' %}">Contact Me</a></li>
            <li><a href="{% url 'main:about' %}">About Me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  {% include "partials/portfolio_visit.html" %}
  <div class="footer-bottom">
    <p>© 2025 Kiarash Seyedmohamadi. All Rights Reserved.</p>
  </div>
</footer>

mysite/templates/partials/header.html
<header class="site-header">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <a class="navbar-brand fw-bold" href="/">{{ main.title|default:"Home" }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navMenu">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navMenu">
        <ul class="navbar-nav ms-auto">
          <a class="nav-link" href="{% url 'main:projects' %}">Projects</a>
          <li class="nav-item"><a class="nav-link" href="{% url 'skills:skills-list' %}">Skills</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'main:resume' %}">Resume</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'blog:bloglist' %}">Blog</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'comments:send_email_box' %}">Feedback</a></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

mysite/templates/partials/portfolio_visit.html
Portfolio Visits: <span style="color:#2a9d8f; font-weight:bold;">{{ visit }}</span>